name: Docker build	

on:	
  schedule:
  - cron: "0 4 * * 6" # At 04:00 on every weekend.
  workflow_dispatch:	
  push:	
    branches:	
      - master	

jobs:	

  docker:	
    name: 'Docker Image'	
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         config:
         - {
            ros2_distro: "jazzy",
            base_image: "nvidia/cuda",
            base_image_tag: "12.8.1-devel-ubuntu24.04",
            image_name_base: "ste93/convince_people_detector:ubuntu_24.04_jazzy",
            dockerfile: "Dockerfile"
         }         
        #  - {
        #     ros2_distro: "iron",
        #     base_image: "ubuntu",
        #     base_image_tag: "22.04",
        #     image_name_base: "ste93/convince:tour_sim_ubuntu_22.04_iron",
        #     dockerfile: "Dockerfile"
        #  }
    steps:	
    - name: Info
      run: |
       echo "Event type: ${{github.event_name}}"
    - name: Change docker to experimental mode
      run: |
       sudo rm -rf /etc/docker/daemon.json
       echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
    - name: Restart docker daemon
      run: sudo systemctl restart docker
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ste93
        password: ${{ secrets.DOCKER_PUSH_KEY }}
    - name: Build the tour core Docker image
      working-directory: docker
      run: |
       if [ ${{ github.event_name }} == 'schedule' ]; then
          echo "Building development image"
          sudo docker build --build-arg base_img=${{matrix.config.base_image}}:${{matrix.config.base_image_tag}} -t ${{matrix.config.image_name_base}}_devel -f ${{matrix.config.dockerfile}} .
       elif [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
          echo "Building stable image"
          echo $PWD
          sudo docker build --build-arg base_img=${{matrix.config.base_image}}:${{matrix.config.base_image_tag}} -t ${{matrix.config.image_name_base}}_stable -f ${{matrix.config.dockerfile}} .
       else
          echo "Failure!"
          exit 1
       fi
    - name: Push tourCore2 image
      working-directory: docker
      run: |
       if [ ${{ github.event_name }} == 'schedule' ]; then
          echo "Pushing tourCore2 development image"
          docker push ${{matrix.config.image_name_base}}_devel
       elif [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
          echo "Pushing tourCore2 stable image"
          docker push ${{matrix.config.image_name_base}}_stable
       else
          echo "Failure!"
          exit 1
       fi

